# Generated by Django 3.0.7 on 2020-07-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('to_user', 'from_user', 'related_type'), ('from_user', 'to_user', 'related_type')},
        ),
    ]
